# Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "Rugby Union - Personal"
product_name = "Rugby Union"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "rp2040"

[matrix]
# Define matrix pins, scanning matrix is 15 rows, 10 cols:
row_pins = [
    "PIN_26", "PIN_14", "PIN_9", "PIN_3", "PIN_23",
    "PIN_13", "PIN_21", "PIN_28", "PIN_7", "PIN_4",
    "PIN_2", "PIN_8", "PIN_16", "PIN_22", "PIN_29"
]
col_pins = [
    "PIN_11", "PIN_20", "PIN_15", "PIN_5", "PIN_10",
    "PIN_0", "PIN_6", "PIN_12", "PIN_1", "PIN_27"
]

[layout]
# Physical layout is matrix of 3 rows, 10 cols
rows = 15
cols = 10
layers = 6
matrix_map = """
(0, 0, L)  (0, 1, L)  (1, 2, L)  (2, 3, L)  (3, 4, L)    (5,  5, R)  (8,  6, R)  (6,  7, R)  (9,  8, R)  (7,  9, R)
(4, 0, L)  (1, 1, L)  (2, 2, L)  (3, 3, L)  (4, 4, L)    (10, 5, R)  (10, 6, R)  (11, 7, R)  (12, 8, R)  (13, 9, R)
(5, 0, L)  (6, 1, L)  (7, 2, L)  (8, 3, L)  (9, 4, L)    (14, 5, R)  (11, 6, R)  (12, 7, R)  (13, 8, R)  (14, 9, R)
"""

[rmk]
combo_max_num = 32

[[layer]]
name = "HD Promethium"
keys = """
Escape P     G     M     K                       Dot BackSpace Quote Minus Equal
S      N     T     H     J                     Comma         A     E     E     C
B      F     D     L     TH(R,LShift)    LT(1,Space)         U     O     Y     W
"""

[[layer]]
name = "Num + Nav"
keys = """
KpSlash    1    2    3    KpPlus        PageUp BackSpace    Up SHIFTED(Minus) MediaPlayPause
KpAsterisk 4    5    6    KpMinus     PageDown      Left  Down          Right     AudioVolUp
Dot        7    8    9    0                 __      Home Enter            End   AudioVolDown
"""

[behavior.fork]
forks = [
  # Shift + '.' outputs shift+semicolon for ':' key
  { trigger = "Dot", negative_output = "Dot", positive_output = "WM(Semicolon, LShift)", match_any = "LShift|RShift" },
  # Shift + ',' outputs ';' key
  { trigger = "Comma", negative_output = "Comma", positive_output = "Semicolon", match_any = "LShift|RShift" },
  # Shift + ' (single quote) outputs S(2) for " (double quote on UK/GB layout)
  { trigger = "Quote", negative_output = "Comma", positive_output = "WM(2, LShift)", match_any = "LShift|RShift" },
  # Left-shift + space (left thumb-shift held, tap right thumb) outputs 'R' key
  # However, right-shift + space still gives shift+space for reverse pagination etc.
  { trigger = "LT(1,Space)", negative_output = "Space", positive_output = "WM(Space, LShift)", match_any = "LShift" },
]

[behavior.combo]
timeout = "50ms"
combos = [
  # Letters on 2-key horizontal combos (layer 0 only)
  { actions = ["P", "G"], output = "V", layer = 0 },
  { actions = ["G", "M"], output = "Q", layer = 0 },
  { actions = ["F", "D"], output = "X", layer = 0 },
  { actions = ["Quote", "Minus"], output = "Z", layer = 0 },
  # Three-key combos for tab and enter
  { actions = ["F", "D", "L"], output = "Tab", layer = 0 },
  { actions = ["U", "O", "Y"], output = "Enter", layer = 0 },
  # Symbols on 2-key vertical combos
  { actions = ["Escape", "S"], output = "Grave", layer = 0 }, # backtick
  { actions = ["P", "N"], output = "SHIFTED(Quote)", layer = 0 }, # at-sign on UK layout
  { actions = ["G", "T"], output = "SHIFTED(NonusBackslash)", layer = 0 },
  { actions = ["M", "H"], output = "SHIFTED(4)", layer = 0 }, # dollar
  { actions = ["K", "J"], output = "SHIFTED(5)", layer = 0 }, # percent
  { actions = ["Dot", "Comma"], output = "SHIFTED(6)", layer = 0 }, # caret
  { actions = ["BackSpace", "A"], output = "SHIFTED(Slash)", layer = 0 }, # question-mark
  { actions = ["Quote", "E"], output = "NonusHash", layer = 0 }, # hash
  { actions = ["Minus", "I"], output = "SHIFTED(1)", layer = 0 }, # exclamation-mark
  { actions = ["Equal", "C"], output = "SHIFTED(NonusHash)", layer = 0 }, # tilde
  # Brackets etc on 2-key horizontal inner combos
  { actions = ["M", "K"], output = "NonusBackslash", layer = 0 }, # \
  { actions = ["Backspace", "Dot"], output = "Slash", layer = 0 }, # /
  { actions = ["H", "K"], output = "SHIFTED(LeftBracket)", layer = 0 }, # {
  { actions = ["A", "Dot"], output = "SHIFTED(RightBracket)", layer = 0 }, # }
  { actions = ["H", "J"], output = "SHIFTED(9)", layer = 0 }, # (
  { actions = ["A", "Comma"], output = "SHIFTED(0)", layer = 0 }, # )
  { actions = ["L", "J"], output = "LeftBracket", layer = 0 }, # [
  { actions = ["U", "Comma"], output = "RightBracket", layer = 0 }, # ]
  # Thumbs
  { actions = ["TH(R,LShift)", "LT(1,Space)"], output = "CapsWordToggle", layer = 0 },  
 ]

[host]
# Vial Unlock combination: simultaneous press of specified keys
unlock_keys = [[0, 0], [0, 9]]  # Q and P
